### ISSUE TITLE
Resource Labs

### ISSUE THREAD

**Issue by willwatters** [willwatters/SEBC#3]

**Comment by rafaelarana** [comment]
Good. You just capture YARN Chart but not the YARN "Applications Charts"

 In CM, navigate to "YARN Applications"

Select the Charts tab and take a screenshot.
Save it to resources/labs/5_YARN_Charts.png

**Comment by willwatters** [comment]
Thanks Rafael - I do have this already captured IN resources/labs/5_YARN_Charts2.png & 5_YARN_Charts3.png as I uploaded multiple screenshots to GitHub.

**Comment by willwatters** [comment]
> Good. You just capture YARN Chart but not the YARN "Applications Charts"
> 
> In CM, navigate to "YARN Applications"
> 
> Select the Charts tab and take a screenshot.
> Save it to resources/labs/5_YARN_Charts.png

Thanks Rafael - I do have this already captured IN resources/labs/5_YARN_Charts2.png & 5_YARN_Charts3.png as I uploaded multiple screenshots to GitHub.
